# has been enable for defconfig
# CONFIG_CONSOLE=y
# CONFIG_SERIAL=y
# CONFIG_UART_CONSOLE=y
# CONFIG_GPIO=y

CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y

CONFIG_I2C=y
CONFIG_SENSOR=y
# CONFIG_MPU6050_TRIGGER_NONE=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_LM75=y

# CONFIG_SPI=y

CONFIG_PWM=y

# Please manually calibrate the sensor here 
# sensor_real_value = raw_value - sensor_adjust
CONFIG_PRESSURE_SENSOR_ADJUST=0

CONFIG_REBOOT=y

CONFIG_FLASH=y

# CONFIG_ADC=y

CONFIG_ESP32_WIFI_STA_AUTO_DHCPV4=y

# 尽可能早的初始化console，可以打印出boot信息
CONFIG_EARLY_CONSOLE=y

CONFIG_NETWORKING=y
CONFIG_TEST_RANDOM_GENERATOR=y

CONFIG_MAIN_STACK_SIZE=5200
CONFIG_SHELL_STACK_SIZE=5200
CONFIG_NET_TX_STACK_SIZE=2048
CONFIG_NET_RX_STACK_SIZE=2048

CONFIG_NET_PKT_RX_COUNT=10
CONFIG_NET_PKT_TX_COUNT=10
CONFIG_NET_BUF_RX_COUNT=20
CONFIG_NET_BUF_TX_COUNT=20
CONFIG_NET_MAX_CONTEXTS=10
CONFIG_NET_DHCPV4=y

CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n

CONFIG_NET_TCP=y

CONFIG_LOG=y

CONFIG_NET_LOG=y
CONFIG_INIT_STACKS=y

CONFIG_KERNEL_SHELL=y
CONFIG_NET_SHELL=y
CONFIG_I2C_SHELL=y

# 启用网络统计信息收集
# CONFIG_NET_STATISTICS=y
# CONFIG_NET_STATISTICS_PERIODIC_OUTPUT=n

CONFIG_WIFI=y
CONFIG_WIFI_LOG_LEVEL_ERR=y
CONFIG_NET_L2_WIFI_SHELL=y
# printing of scan results puts pressure on queues in new locking
# design in net_mgmt. So, use a higher timeout for a crowded
# environment.
# Timeout for event queue
CONFIG_NET_MGMT_EVENT_QUEUE_TIMEOUT=5000
CONFIG_NET_MGMT_EVENT_QUEUE_SIZE=16
